### ISSUE TITLE
Excessive memory consumption

### ISSUE THREAD

**Issue by maryo** [staabm/phpstan-todo-by#103]
Hello. Thanks for the cool package.
We use it in a large project. After upgrading from 0.1.21, memory consumption vastly increased from 1.5 GB to 4.09 GB. The first problematic version is 0.1.22, 0.1.27 has the same problem. I really upgraded just this single package, nothing more.

**Comment by staabm** [comment]
Hey. Could you give us a example which reproduces the problem?

**Comment by staabm** [comment]
@maryo please test the latest release.

**Comment by staabm** [comment]
pushed another release with a [fix](https://github.com/staabm/phpstan-todo-by/pull/105). please give it a try and report back when the problem is still reproducible

**Comment by staabm** [comment]
https://github.com/staabm/phpstan-todo-by/releases/tag/0.1.31 should fix it
