### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by m29corey** [staabm/phpstan-todo-by#3]
Few things that I suggest:

1. Make the code case-insensitive. This would include changing the pattern by adding an "i" after the closing slash, and change other string comparison sections to make the subject match case of the comparison.
2. Add an optional "@" to the start of the pattern.
I preface my todo comments with "@" for IDE highlighting reasons.
4. Use named capture groups in the regular expression:
`'/^TODO:?\s*(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2}):?(?P<comment>.*)$/'`
You can then reference these names rather than integer indexes in the $matches array.
Details about it can be found here: https://www.php.net/manual/en/regexp.reference.subpatterns.php
5. Make your variable interpolation consistent.

**Comment by staabm** [comment]
> 1. Make the code case-insensitive. This would include changing the pattern by adding an "i" after the closing slash, and change other string comparison sections to make the subject match case of the comparison.

I did this intentionally to reduce the performance impact of the rule. it might make sense make it configurable so people which prefer e.g. lowercase `// todo` can be supported

> 2\. Add an optional "@" to the start of the pattern.
>         I preface my todo comments with "@" for IDE highlighting reasons.

how do your comments look like, please provde a example

> 3\. Use named capture groups in the regular expression:

I am fine with the pattern as is

> 4\. Make your variable interpolation consistent.

feel free to provide a PR if this is something importan to you :-)

**Comment by voku** [comment]
> 2. Add an optional "@" to the start of the pattern.
> I preface my todo comments with "@" for IDE highlighting reasons.

I also add "@" for the same reason, it looks like this: https://www.jetbrains.com/help/phpstorm/using-todo.html#add_pattern_filter_todo 

e.g. `TODO@lars -> ...`

**Comment by apfelbox** [comment]
I would love support for `@todo`, as that is the format we typically use.

**Comment by staabm** [comment]
> I would love support for `@todo`, as that is the format we typically use.

could you give a complete example of how your comment looks like

**Comment by m29corey** [comment]
Here is a couple of examples of an `@todo` from one of my projects:

```
/**
 * @todo - Convert to standard Drupal $content code.
 */
...
// @todo Decide to fix all the broken instances of class as a string
```
Some comments have the hyphen, some don't.

**Comment by m29corey** [comment]
I made a pull request with my suggested changes, and added in support for php doc comments.
I tested this on a large project and saw no significant performance loss compared to PHPStan not using this plugin.
