### ISSUE TITLE
Idea: todo expire todo when PR is released

### ISSUE THREAD

**Issue by nikophil** [staabm/phpstan-todo-by#49]
Hi!

not sure you'll like this one, as it is a logic suite of https://github.com/staabm/phpstan-todo-by/issues/31, but going a little bit further :sweat_smile: 

Something I'd find really useful would be to expire todo comments based on a vendor PR link: when the PR is merged and released, and vendor meets the release version in your dependencies.

I've seen a lot of projects cluttered with comments like this:
```php
// todo: remove this workaround when https://github/vendor/lib/pull/1234 is released
```
and these todos are only fixed if by chance someone some day sees the comment and gives it some attention.

GitHub exposes in its api the first release when a PR appears. So, I think it could leverage the work done in #32

WDYT?

**Comment by staabm** [comment]
We could implement a todo-by-ticket github-issues fetcher todo that.

This should work for github issues and PRs 


Just enhance the rule implemented with https://github.com/staabm/phpstan-todo-by/pull/26 with a new fetcher

**Comment by staabm** [comment]
the refined-github browser extensions renders a note in PRs which have been merged and are part of a PR:

![grafik](https://github.com/staabm/phpstan-todo-by/assets/120441/b06f6294-a18b-4007-8d65-c43c988af2b9)

https://github.com/refined-github/refined-github/blob/a101ac6513d71173d4c5788b999129d812823046/source/features/closing-remarks.tsx#L78-L91

you might find some inspiration there

**Comment by nikophil** [comment]
haha I didn't even know this information was added by this addon, I used since so long time 😅

https://github.com/refined-github/refined-github/blob/a101ac6513d71173d4c5788b999129d812823046/source/features/closing-remarks.tsx#L21-L31

they look into this url and hack into the html
https://github.com/staabm/phpstan-todo-by/branch_commits/98d37d9dcfbcf1a70bb7a36ecea7c6ca7430c347

**Comment by staabm** [comment]
Hmm I would prefer a more api centric approach

**Comment by staabm** [comment]
issue/pr closed state handling was implemented with https://github.com/staabm/phpstan-todo-by/pull/62

as you pointed out the 'released' state is not easily to determine. until github.com provides a proper mean to detect this state I will close this issue for now.

thanks for the feedback though
