### ISSUE TITLE
UX: better readable date format

### ISSUE THREAD

**Issue by staabm** [staabm/phpstan-todo-by#5]
consider using a more human readable date format, e.g. with month as a written word

```
// TODO: 2023 December 14 Expired comment1
```

goal: make it clear which part of the date is the day and which is the month

----

the dateformat implemented initially is the one used by the projects which this extension got inspiration from.
we might support both formats. we should stay compatible with the inspiring repos.

we need to check whether adding more formats has a perf impact

**Comment by dereuromark** [comment]
As clearly identifiable ISO date it is already clear which part is what IMO.
Thats international standard for a reason

**Comment by staabm** [comment]
There are so many date formats and depending on country / region expectations area different. 

I just had the idea, that we could validate the date format ranges to make it a bit more stable.
