### ISSUE TITLE
DX: Define error identifiers

### ISSUE THREAD

**Issue by EmilMassey** [staabm/phpstan-todo-by#82]
In phpstan 1.11 [error identifiers](https://phpstan.org/error-identifiers) will be available for use to ignore specific errors. We can already use `PHPStan\Rules\RuleErrorBuilder::identifier()` to define custom identifiers for errors reported by this extension.  They will be useful when 1.11 is released.

I think it would be a nice feature to have. If we want to have it, we should discuss what the identifiers should look like, eg. `todo_by.date`, `todo_by.ticket`, etc.

**Comment by staabm** [comment]
I think we can start with one error per rule. phpstan seems to use camel case for them.

**Comment by staabm** [comment]
implemented in https://github.com/staabm/phpstan-todo-by/pull/83
