### ISSUE TITLE
Respect configurable vendor folder location

### ISSUE THREAD

**Issue by DanielSiepmann** [staabm/phpstan-todo-by#85]
This can be seem as follow up to https://github.com/staabm/phpstan-todo-by/pull/54#discussion_r1440652936

We now have a project where best practices define to move the vendor folder. This is pretty common for TYPO3 Extension. You can find the repository here: https://github.com/FriendsOfTYPO3/tea it serves as a best practice for the community and we want to add the to do extension.

But that doesn't work due to the different vendor location. It therefore would be cool if the extension would read the location and that way support the actual path.

**Comment by staabm** [comment]
Using a non-standard vendor folder brings a lot of problems with different tools.

I would warn you to recommend this to a whole community. 

I am also not willing to build a PR for such a way of stuff as I really don't like this idea. 

That said, in case you provide a automated test and the fix does not require a lot of changes, I am open for a contribution

**Comment by DanielSiepmann** [comment]
I'm not aware of any issues. I also do not use that, but the community decided it is best practice.

Thanks for your honesty. I fully understand that and believe in the right as maintainer to decide so.

I'll use your refusal to discuss the vendor location with the best practices team. I'll close the issue for now. I might re-open it if we decide to contribute with testing.

**Comment by staabm** [comment]
from the top of my head:
- `vendor` is a php ecosystem wide default, every php developer used to composer knows. having a different location and/or name for this folder is a exception every developer needs to learn to apply with TYPO3 recommendations
- using a different location and or name means, every tool you want to use needs to support your use-case (see e.g. this feature request here)
- some tools have sane defaults for the `vendor/` folder, which eases initial setup and improves developer experience. using a different vendor folder means you need additional manual configuration/quirks to make the tools know 'your vendor' folder
- I remember @ocramius has a special place in his heart for people who deviate from the eco-system wide default ;-)

**Comment by Ocramius** [comment]
> has a special place in his heart for people who deviate from the eco-system wide default ;-)

It's really just your same reasoning: tons and tons of complexity. Imagine moving the `.git` directory and expecting all git-related tools to work 😱
