### ISSUE TITLE
Set level by env

### ISSUE THREAD

**Issue by damien-louis** [staabm/phpstan-todo-by#9]
Good idea this extension!

It's possible to set level alert by environment?   
For example, to be free to decide to trigger just a warning in dev mode, test mode, but error prod mode. 

The goal is to configure github actions/gitlab CI to just set a warning when push commit but block merged in main if error is triggered.

**Comment by staabm** [comment]
What do you mean by alert-level?

Phpstan does not has concepts like notices or warnings. Everything is an error.

**Comment by damien-louis** [comment]
Ok, I wasn't sure if phpstan allow to set warning instead of error

**Comment by damien-louis** [comment]
Thanks for your answer
