### ISSUE TITLE
Registering of new TODOs in JIRA

### ISSUE THREAD

**Issue by Aeliot-Tm** [staabm/phpstan-todo-by#99]
Thank you for the package. I like it and I'm going to automate registering of new TODOs in JIRA by CI job.

The main idea is (expected behavior):
- developers add some TODO/FIXME so on in the code. They are totally free in it and don't spend time on creation of tickets in JIRA.
- some script register tickets in JIRA and add their numbers into the code.
- last changes committed automatically at the end of job.

Pros:
- All TODOs has linked issues in JIRA and manages can plan their fixing. 
- No one TODO is forgot.

Could you suggest package for this purpose?

**Comment by staabm** [comment]
you can take inspiration of the existing `*Rule` classes, which utilize the `CommentMatcher` to detect the `Todo` comments.

with the information of this comments you can trigger calls against the JIRA api.
I am not sure how useful your suggested approach is though, as your plan might spam your jira instance with tickets.

I guess it kind of depends at which point in time you do the "sync"/"detect" of TODO comments and trigger the ticket creation.

I will close this issue for now, feel free to ask further questions

**Comment by Aeliot-Tm** [comment]
Hi @staabm,

Yeah, it may be noising but it is expected behavior. I'd like to solve 2 problems from my side.

The firs one. Developers add TODOs and forget about them soon. And managers know nothing about them. So, nobody do something with them and code become poisoned soon. I'd like to keep it clean.

The second one. I'd like to add some tags into the code when I review projects. And get prepared tickets in JIRA without spending of time on clicking in browser and filling lots of fields.

I spend several days on seeking if of required package and did not found necessary package. So, I'm going to implement it myself.

Thanks, a lot for your time.

**Comment by Aeliot-Tm** [comment]
Hi @staabm,

I released the firs version of [TODO Registrar](https://github.com/Aeliot-Tm/todo-registrar). I'm going to improve it and make it more compatible with your project. I would be nice when you could spend a little time to look through it. And maybe recommend it when you find it useful.

Kind regards, 
Anatoliy.
